# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ ../nixpkgs/nixos/modules/installer/scan/not-detected.nix
    ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/47adcd08-5a1e-4d15-9ae1-97459638e903";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/44a32c4f-6b6a-43d6-970b-f4398fbd855b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-id/ata-INTEL_SSDSC2KW480H6_CVLT61850B1Q480EGN-part2";
      fsType = "vfat";
    };
  fileSystems."/boot2" =
    { device = "/dev/disk/by-id/ata-INTEL_SSDSC2BW180A4_CVDA447006A31802GN-part2";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c2edd44c-fe0e-4a7d-abe4-e2433e537d60"; }
    ];

  nix.maxJobs = 2;
}
